version: "3.8"

services:
  api:
    container_name: api-real-time-chat
    build: ./.docker/api
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./:/home/node/app
    networks:
      - real-time-chat-net

  redis:
    container_name: redis-real-time-chat
    image: bitnami/redis:7.2.4
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis
    environment:
      - REDIS_PASSWORD=redis-password-docker
    networks:
      - real-time-chat-net

  mongodb:
    container_name: mongodb-real-time-chat
    build: ./.docker/mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: docker-password-docker
      MONGO_INITDB_ROOT_USERNAME: docker-username-docker
      MONGO_REPLICA_HOST: mongodb
      MONGODB_DATABASE: real-time-chat
    networks:
      - real-time-chat-net

networks:
  real-time-chat-net:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
