version: "3.8"

services:
  api:
    container_name: api-magic-link
    build: ./.docker/api
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./:/home/node/app
    networks:
      - magic-link-net

  redis:
    container_name: redis-magic-link
    image: bitnami/redis:7.2.4
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis
    environment:
      - REDIS_PASSWORD=redis-password-docker
    networks:
      - magic-link-net

  mongodb:
    container_name: mongodb-magic-link
    build: ./.docker/mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: docker-password-docker
      MONGO_INITDB_ROOT_USERNAME: docker-username-docker
      MONGO_REPLICA_HOST: mongodb
      MONGODB_DATABASE: magic-link
    networks:
      - magic-link-net

  mailpit:
    image: axllent/mailpit
    container_name: mailpit-magic-link
    environment:
      MP_DATA_FILE: /data/mailpit.db
      MP_UI_BIND_ADDR: 0.0.0.0:8025
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
      TZ: America/Sao_Paulo
    ports:
      - 8025:8025
    volumes:
      - mailpit_data:/data
    networks:
      - magic-link-net

networks:
  magic-link-net:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  mailpit_data:
